### ISSUE TITLE
缺少helper文件

### ISSUE THREAD

**Issue by zhengxiaoxuer** [duterscmy/ccks2019-ckbqa-4th-codes#1]
你好，我看到您上传的程序中好像没有helper文件，请问能不能提供用于生成一些字典/语料集预处理的程序文件，十分感谢!

**Comment by duterscmy** [comment]
晚上我把程序传到github上哈



---原始邮件---
发件人: "zhengxiaoxuer"<notifications@github.com&gt;
发送时间: 2019年10月30日(星期三) 下午2:38
收件人: "duterscmy/ccks2019-ckbqa-4th-codes"<ccks2019-ckbqa-4th-codes@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [duterscmy/ccks2019-ckbqa-4th-codes] 缺少helper文件 (#1)



你好，我看到您上传的程序中好像没有helper文件，请问能不能提供用于生成一些字典/语料集预处理的程序文件，十分感谢!

**Comment by zhengxiaoxuer** [comment]
感谢作者回复！请问您提供的ccks2018 COQA评测第二名论文有没有相应的代码，我在github 上只搜到第一名的，还是您根据论文自己复现的？

**Comment by duterscmy** [comment]
没有提供，是自己复现的，后来改成了现在我们的版本。



---原始邮件---
发件人: "zhengxiaoxuer"<notifications@github.com&gt;
发送时间: 2019年10月30日(星期三) 下午4:06
收件人: "duterscmy/ccks2019-ckbqa-4th-codes"<ccks2019-ckbqa-4th-codes@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Caomingyu"<1054527636@qq.com&gt;;
主题: Re: [duterscmy/ccks2019-ckbqa-4th-codes] 缺少helper文件 (#1)



感谢作者回复！请问您提供的ccks2018 COQA评测第二名论文有没有相应的代码，我在github 上只搜到第一名的，还是您根据论文自己复现的？

**Comment by zhengxiaoxuer** [comment]
好的，感谢，期待helper程序。

**Comment by MrRace** [comment]
`all_mentions_train.pkl`和`corpus_train.pkl`等中间数据也是基于`helper`下的脚本从原始数据生成的吧？

**Comment by duterscmy** [comment]
前者不是，后者是，代码太乱了2333有空把readme.md再写的详细些



---原始邮件---
发件人: "JaonLiu"<notifications@github.com&gt;
发送时间: 2019年10月30日(星期三) 下午5:05
收件人: "duterscmy/ccks2019-ckbqa-4th-codes"<ccks2019-ckbqa-4th-codes@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Caomingyu"<1054527636@qq.com&gt;;
主题: Re: [duterscmy/ccks2019-ckbqa-4th-codes] 缺少helper文件 (#1)



all_mentions_train.pkl和corpus_train.pkl等中间数据也是基于helper下的脚本从原始数据生成的吧？

**Comment by MrRace** [comment]
那`all_mentions_train.pkl`是怎么生成的？好像没有说。。。。蓝瘦香菇.jpg

**Comment by duterscmy** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        就是先运行mention_extractor再运行prop_extractor，得到的结果文件就是all_mentions了
        
    
        
            
        
    
    
        
        

        
    

    在2019年10月30日 18:41，JaonLiu<notifications@github.com> 写道： 


那all_mentions_train.pkl是怎么生成的？好像没有说。。。。蓝瘦香菇.jpg

**Comment by MrRace** [comment]
其他字典我已经生成了，`question_2_mention.pkl` 具体怎么生成的？有劳补充下脚本~谢谢！

**Comment by ZainZhou** [comment]
> 其他字典我已经生成了，`question_2_mention.pkl` 具体怎么生成的？ @duterscmy 有劳补充下脚本~谢谢！

老哥你用这个代码跑起来了吗？
