### ISSUE TITLE
PKUBASE知识库处理成neo4j-admin import可以导入的数据

### ISSUE THREAD

**Issue by MrRace** [duterscmy/ccks2019-ckbqa-4th-codes#10]
已经安装了neo4j数据库。PKUBASE知识库源文件需要处理成可以 让 neo4j-admin import的格式。为了能够保持这部分数据格式与您数据格式的一致性，从而确保后续查询语句可以套用，希望您能够提供下这部分预处理的脚本或者neo4j-admin import 导入的样例数据。最好是有完整的处理脚本，谢谢！

**Comment by duterscmy** [comment]
传到src里了

**Comment by MrRace** [comment]
> 传到src里了

感谢作者~
