### ISSUE TITLE
想问一下ner_model.h5是什么文件

### ISSUE THREAD

**Issue by ZainZhou** [duterscmy/ccks2019-ckbqa-4th-codes#11]
请问这是其他地方训练好的预训练模型吗？还是什么？大佬帮给我讲讲

**Comment by duterscmy** [comment]
就是在bert上加了层全连接，然后保存为keras格式的h5模型。在train_ner.py里生成的。



---原始邮件---
发件人: "Zain"<notifications@github.com&gt;
发送时间: 2019年11月26日(星期二) 晚上9:12
收件人: "duterscmy/ccks2019-ckbqa-4th-codes"<ccks2019-ckbqa-4th-codes@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [duterscmy/ccks2019-ckbqa-4th-codes] 想问一下ner_model.h5是什么文件 (#11)



请问这是其他地方训练好的预训练模型吗？还是什么？大佬帮给我讲讲

**Comment by ZainZhou** [comment]
好像是我Mac系统上的h5py包有点问题，我检查一下，因为运行train_ner.py一直报错。

`    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = '../data/model/ner_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)`

**Comment by ZainZhou** [comment]
请问一下大佬，/news_classifer_task/wwm/文件夹中的文件就是直接从chinese_L-12_H-768_A-12里解压出来的对吧？vocab.txt和bert模型和配置那些

**Comment by miaozjs** [comment]
我也碰见这个问题ner_model.h5无法打开，也无法生成，请问你解决了吗

**Comment by duterscmy** [comment]
对的



---原始邮件---
发件人: "Zain"<notifications@github.com&gt;
发送时间: 2019年11月27日(星期三) 下午3:25
收件人: "duterscmy/ccks2019-ckbqa-4th-codes"<ccks2019-ckbqa-4th-codes@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Caomingyu"<1054527636@qq.com&gt;;
主题: Re: [duterscmy/ccks2019-ckbqa-4th-codes] 想问一下ner_model.h5是什么文件 (#11)



请问一下大佬，/news_classifer_task/wwm/文件夹中的文件就是直接从chinese_L-12_H-768_A-12里解压出来的对吧？vocab.txt和bert模型和配置那些

**Comment by duterscmy** [comment]
> 我也碰见这个问题ner_model.h5无法打开，也无法生成，请问你解决了吗

好像是因为得自己建data/model这个路径..

**Comment by duterscmy** [comment]
> 好像是我Mac系统上的h5py包有点问题，我检查一下，因为运行train_ner.py一直报错。
> 
> ` fid = h5f.open(name, flags, fapl=fapl) File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper File "h5py/h5f.pyx", line 88, in h5py.h5f.open OSError: Unable to open file (unable to open file: name = '../data/model/ner_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)`



> 好像是我Mac系统上的h5py包有点问题，我检查一下，因为运行train_ner.py一直报错。
> 
> ` fid = h5f.open(name, flags, fapl=fapl) File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper File "h5py/h5f.pyx", line 88, in h5py.h5f.open OSError: Unable to open file (unable to open file: name = '../data/model/ner_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)`

我今天也遇到这个问题了，手动建一下路径就好了，上传代码的时候文件夹没完全传上来

**Comment by Rilzob** [comment]
这个问题应该是145行多出来一句：
model = load_model('src/data/model/ner_model.h5', custom_objects=get_custom_objects())
注释掉应该就行了。
