### ISSUE TITLE
询问不使用词向量相似性构建特征的原因

### ISSUE THREAD

**Issue by 1234560o** [duterscmy/ccks2019-ckbqa-4th-codes#14]
作者，您好，计算实体特征只采用了报告中提到的5个特征，而没有使用词向量相似性比较构建特征（我看utils.py文件中有比较相似性特征的函数），这个是出于什么原因考虑呢？

**Comment by duterscmy** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            
        
    
    
        因为不会算，也嫌麻烦。。实体链接这一步计算特征的话，就是拿问题跟实体的子图做匹配，用词向量算相似度我能想到的只有把问题取平均、再把子图取平均算个余弦距离，有比较好的方法可以推荐给我hh
    
        
        

        
    

    在2019年12月6日 15:38，zwj<notifications@github.com> 写道： 


作者，您好，计算实体特征只采用了报告中提到的5个特征，而没有使用词向量相似性比较构建特征（我看utils.py文件中有比较相似性特征的函数），这个是出于什么原因考虑呢？
