### ISSUE TITLE
tuple_extractor.py中的疑问

### ISSUE THREAD

**Issue by MrRace** [duterscmy/ccks2019-ckbqa-4th-codes#2]
首先感谢作者的分享，收益颇多。但是在学习过程存在以下疑问，希望作者能够帮忙解答。
在`tuple_extractor.py`中`entity2relations_dic` 存储为`entity2relation_dic.pkl`，`sentencepair2sim`存储为`sentencepair2sim_dic.pkl`，
(1)但是代码中没有对于``entity2relations_dic` 这个变量处理的逻辑。
(2)代码中`from kb import GetRelationPaths` 但是项目中似乎缺乏这个可以被引入的依赖。希望您能够补充下。
谢谢!

**Comment by duterscmy** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        你好，这个entity2relations就是每个实体对应的所有关系路径的字典，做评测时为了加快速度弄的，实际查询速度很快没啥用就给删了，相关部分删掉就可以。kb.py传上去了，但是我的知识库是在本地服务器搭着用的，所以实际这个程序是无法运行的。
        
    
        
            
        
    
    
        
        

        
    

    在2019年11月1日 10:10，JaonLiu<notifications@github.com> 写道： 


首先感谢作者的分享，收益颇多。但是在学习过程存在以下疑问，希望作者能够帮忙解答。

在tuple_extractor.py中entity2relations_dic 存储为entity2relation_dic.pkl，sentencepair2sim存储为sentencepair2sim_dic.pkl，

(1)但是代码中没有对于``entity2relations_dic 这个变量处理的逻辑。 (2)代码中from kb import GetRelationPaths` 但是项目中似乎缺乏这个可以被引入的依赖。希望您能够补充下。

谢谢!
