### ISSUE TITLE
kb.py

### ISSUE THREAD

**Issue by zhengxiaoxuer** [duterscmy/ccks2019-ckbqa-4th-codes#24]
在运行entity_eextractor.py中，from kb import GetRelations_2hop,GetRelationNum

其中kb.py程序缺少GetRelationNum计算流行度的函数

**Comment by wbq813** [comment]
GetRelationNum没有，怎么解决的

**Comment by Lanme** [comment]
> GetRelationNum没有，怎么解决的

请问解决了么？

**Comment by duterscmy** [comment]
已重新上传~




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Lanme"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月2日(星期一) 下午4:57
收件人:&nbsp;"duterscmy/ccks2019-ckbqa-4th-codes"<ccks2019-ckbqa-4th-codes@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [duterscmy/ccks2019-ckbqa-4th-codes] kb.py (#24)



 
GetRelationNum没有，怎么解决的
  
请问解决了么？

**Comment by Lanme** [comment]
> 已重新上传~
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"Lanme"<notifications@github.com&gt;; 发送时间:&nbsp;2020年3月2日(星期一) 下午4:57 收件人:&nbsp;"duterscmy/ccks2019-ckbqa-4th-codes"<ccks2019-ckbqa-4th-codes@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;Re: [duterscmy/ccks2019-ckbqa-4th-codes] kb.py (#24) GetRelationNum没有，怎么解决的 请问解决了么？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

回复好快，谢谢~
