### ISSUE TITLE
question_2_mention.pkl怎么生成

### ISSUE THREAD

**Issue by zhengxiaoxuer** [duterscmy/ccks2019-ckbqa-4th-codes#3]
您好，感谢作者提供的代码，我运行helper文件程序后，再运行mention_extractor.py,发现缺少question_2_mention.pkl
helper文件没找到生成该字典的程序。

**Comment by duterscmy** [comment]
这个文件本质就是语料集里每个问题对应的bert识别出的实体，我给改成了输入问题直接调用bert模型得到mention的方式，更新了train_ner.py mention_extractor.py kb.py这几个文件，你可以重新下载一下。
train_ner.py得需要去下载谷歌发布的中文预训练模型再执行微调。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"zhengxiaoxuer"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月1日(星期五) 中午1:56
收件人:&nbsp;"duterscmy/ccks2019-ckbqa-4th-codes"<ccks2019-ckbqa-4th-codes@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[duterscmy/ccks2019-ckbqa-4th-codes] question_2_mention.pkl怎么生成 (#3)




您好，感谢作者提供的代码，我运行helper文件程序后，再运行mention_extractor.py,发现缺少question_2_mention.pkl
 helper文件没找到生成该字典的程序。

**Comment by zhengxiaoxuer** [comment]
恩恩感谢！请问您用的requirement及其版本都有哪些

**Comment by zhengxiaoxuer** [comment]
请问keras版本用的哪个，版本问题会报错

**Comment by duterscmy** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    keras2.3.1
        tensorflow 1.14.0 
    
        
            
        
    
    
        
        

        
    

    在2019年11月1日 14:52，zhengxiaoxuer<notifications@github.com> 写道： 


请问keras版本用的哪个，版本问题会报错

**Comment by zhengxiaoxuer** [comment]
我的版本和你的是一样的，最后发现是keras_bert包的问题，更新包之后就可以了，感谢！

**Comment by zhengxiaoxuer** [comment]
@duterscmy       在prop_extractor.py　48行这一部分提取属性值，这里为什么要用question2mention来提取实体？
        try:
            max_props = self.question2mention[QUES][1]
            for p in max_props:
                mark_props[p] = p
        except:
            print('this question dont have long props')
            pass

**Comment by MrRace** [comment]
question_2_mention.pkl这个文件在`prop_extractor.py`还是有用到。那我是在train_ner.py的时候保存train和valid数据集中问句对应的实体吗？

**Comment by duterscmy** [comment]
这个没啥用了，可以删掉。。我个人倾向于在识别实体的时候直接调模型而不是提前保存结果。。评测时候因为是合作的才弄了这个文件

---原始邮件---
发件人: "JaonLiu"<notifications@github.com&gt;
发送时间: 2019年11月19日(星期二) 晚上7:44
收件人: "duterscmy/ccks2019-ckbqa-4th-codes"<ccks2019-ckbqa-4th-codes@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"Caomingyu"<1054527636@qq.com&gt;;
主题: Re: [duterscmy/ccks2019-ckbqa-4th-codes] question_2_mention.pkl怎么生成 (#3)



question_2_mention.pkl这个文件在prop_extractor.py还是有用到。那我是在train_ner.py的时候保存train和valid数据集中问句对应的实体吗？

**Comment by ZainZhou** [comment]
请问作者prop_extractor.py运行后发现recall只有0.31是否过于低了？

```
单主语且主语为属性值问题中，能找到所有主语属性值的比例为:0.31
平均每个问题属性为:1.35
[15, 24, 90, 124, 125, 177, 208, 218, 227, 242, 258, 265, 280, 289, 294, 324, 325, 335, 339, 360, 381, 386, 388, 391]
[292, 343, 356, 370]
得到实体mention
耗费时间61.33秒
```

**Comment by duterscmy** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    不应该啊，我记得正常60%左右的，可以把注释掉的那块模糊匹配加上试试。。我记不清最后用的哪个版本了不好意思
    
        
            
        
    
    
        
        

        
    

    在2019年12月6日 18:47，Zain<notifications@github.com> 写道： 


请问作者prop_extractor.py运行后发现recall只有0.31是否过于低了？

单主语且主语为属性值问题中，能找到所有主语属性值的比例为:0.31

平均每个问题属性为:1.35

[15, 24, 90, 124, 125, 177, 208, 218, 227, 242, 258, 265, 280, 289, 294, 324, 325, 335, 339, 360, 381, 386, 388, 391]

[292, 343, 356, 370]

得到实体mention

耗费时间61.33秒

**Comment by ZainZhou** [comment]
@duterscmy 模糊匹配加上也效果很差，而且加上之后速度特别慢。想请问一下 `entity_mention = corpus[i]['entity_mention']`从之前mention_extractor.py生成的entity_mention字段为什么在prop_extractor.py里导入了但是没有使用？是不是因为没有用这个的原因呢？

**Comment by duterscmy** [comment]
你这个环节的数值是在测试集评价的？验证集上应该是60%+的，因为这个知识库的属性值比较不规范，所以感觉很难提上去。跟entity mention应该没关系。



---原始邮件---
发件人: "Zain"<notifications@github.com&gt;
发送时间: 2019年12月7日(周六) 下午3:26
收件人: "duterscmy/ccks2019-ckbqa-4th-codes"<ccks2019-ckbqa-4th-codes@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"Caomingyu"<1054527636@qq.com&gt;;
主题: Re: [duterscmy/ccks2019-ckbqa-4th-codes] question_2_mention.pkl怎么生成 (#3)



@duterscmy 模糊匹配加上也效果很差，而且加上之后速度特别慢。想请问一下 entity_mention = corpus[i]['entity_mention']从之前mention_extractor.py生成的entity_mention字段为什么在prop_extractor.py里导入了但是没有使用？是不是因为没有用这个的原因呢？

**Comment by ZainZhou** [comment]
@duterscmy 我是在valid上跑的，不是测试集呀

**Comment by ZainZhou** [comment]
@duterscmy 还有一个问题就是在tuple_filter.py中在获取feature时的维度问题。
```
            if len(gold_tuple) == len(set(gold_tuple).intersection(set(t))):
                X.append([features[9][0][1]])
                Y.append([1])
            else:
                X.append([features[9][0][1]])
                Y.append([0])
```
在tuple_extractor.py生成的feature里只有['entity','mention',sim2]三个呀

**Comment by ZainZhou** [comment]
@duterscmy answer_bot.py运行会报`AttributeError: 'AnswerByPkubase' object has no attribute 'correct_index'`

**Comment by duterscmy** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        是的..本来有一些相似度特征..后来发现单独用微调后的bert效果就很好了..但是为了方便后续加其他特征代码结构就还是这样写的
        
    
        
            
        
    
    
        
        

        
    

    在2019年12月8日 00:36，Zain<notifications@github.com> 写道： 


@duterscmy 还有一个问题就是在tuple_filter.py中在获取feature时的维度问题。

            if len(gold_tuple) == len(set(gold_tuple).intersection(set(t))):

                X.append([features[9][0][1]])

                Y.append([1])

            else:

                X.append([features[9][0][1]])

                Y.append([0])



在tuple_extractor.py生成的feature里只有['entity','mention',sim2]三个呀
