### ISSUE TITLE
train_ner.py命名实体识别f值低

### ISSUE THREAD

**Issue by zhengxiaoxuer** [duterscmy/ccks2019-ckbqa-4th-codes#4]
您好，我跑您提供的训练命名实体识别的的代码，ｆ值一直都是0.6５左右。识别率好低，请问您当时命名实体识别部分的f值是多少？

**Comment by duterscmy** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    我也是这么高，因为只在这个数据集上微调语料太少。我人工看了下结果，如果是作为jieba分词的补充的话准确率够了，如果想要更高准确率的话可以参考         https://github.com/macanv/BERT-BiLSTM-CRF-NER这个项目，但是用起来有些麻烦。
    
        
            
        
    
    
        
        

        
    

    在2019年11月2日 11:18，zhengxiaoxuer<notifications@github.com> 写道： 


您好，我跑您提供的训练命名实体识别的的代码，ｆ值一直都是0.6５左右。识别率好低，请问您当时命名实体识别部分的f值是多少？

**Comment by zhengxiaoxuer** [comment]
嗯嗯好的。我跑完train_ner后，再跑mention_extractor.py出现oom的错误，进程直接被kill。是内存的原因吗？

**Comment by duterscmy** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        对 因为那个分词词典太大了 得在服务器上跑  内存不够的话可以只用bert识别出来的
        
    
        
            
        
    
    
        
        

        
    

    在2019年11月2日 15:54，zhengxiaoxuer<notifications@github.com> 写道： 


嗯嗯好的。我跑完train_ner后，再跑mention_extractor.py出现oom的错误，进程直接被kill。是内存的原因吗？

**Comment by zhengxiaoxuer** [comment]
只用bert命名实体识别模型准确率会低吗？

**Comment by duterscmy** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        我没评价过，因为实体识别这一步单独没法衡量准确度，语料里只给了知识库里的实体，所以得跑到entity_extractor这一步也就是链接到知识库上，才能衡量一下召回率。你可以试一下，如果召回率不到90%的话，可以考虑自己写一个n-gram完全匹配来替代jieba分词。
    
        
            
        
    
    
        
        

        
    

    在2019年11月2日 19:12，zhengxiaoxuer<notifications@github.com> 写道： 


只用bert命名实体识别模型准确率会低吗？

**Comment by duterscmy** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        我们当时做评测的时候是jieba和bert一起用的，然后链接到知识库之后评价了一下召回率。单独bert没试过呢
        
    
        
            
        
    
    
        
        

        
    

    在2019年11月2日 19:15，曹明宇<1054527636@qq.com> 写道： 




    font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        我没评价过，因为实体识别这一步单独没法衡量准确度，语料里只给了知识库里的实体，所以得跑到entity_extractor这一步也就是链接到知识库上，才能衡量一下召回率。你可以试一下，如果召回率不到90%的话，可以考虑自己写一个n-gram完全匹配来替代jieba分词。
    
        
            
        
    
    
        
        

        
    

    在2019年11月2日 19:12，zhengxiaoxuer<notifications@github.com> 写道： 


只用bert命名实体识别模型准确率会低吗？

**Comment by ZainZhou** [comment]
@duterscmy 在entity_filter.py执行后，在验证集上逻辑回归top5筛选后，所有问题实体召回率为0.702，单实体问题实体召回率0.817。 报告中是0.897，与0.702差了19个点，不知道是什么原因导致的。

**Comment by duterscmy** [comment]
我有时间再跑一次看看问题出在哪了哈



---原始邮件---
发件人: "Zain"<notifications@github.com&gt;
发送时间: 2019年12月9日(周一) 晚上9:00
收件人: "duterscmy/ccks2019-ckbqa-4th-codes"<ccks2019-ckbqa-4th-codes@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"Caomingyu"<1054527636@qq.com&gt;;
主题: Re: [duterscmy/ccks2019-ckbqa-4th-codes] train_ner.py命名实体识别f值低 (#4)



@duterscmy 在entity_filter.py执行后，在验证集上逻辑回归top5筛选后，所有问题实体召回率为0.702，单实体问题实体召回率0.817。 报告中是0.897，与0.702差了19个点，不知道是什么原因导致的。
