### ISSUE TITLE
第一次运行train_ner.py的时候，提示找不到../data/model/ner_model.h5/{saved_model.pbtxt|saved_model.pb}

### ISSUE THREAD

**Issue by HankTown** [duterscmy/ccks2019-ckbqa-4th-codes#49]
谢谢作者的代码分享，我按照你给的步骤做，运行train_ner.py时，在以下行报错：
`model = load_model('../data/model/ner_model.h5', custom_objects=get_custom_objects())`
错误信息为：
`OSError: SavedModel file does not exist at: ../data/model/ner_model.h5/{saved_model.pbtxt|saved_model.pb}`
请问这个文件第一次运行时怎么生成呢？

**Comment by pen-ho** [comment]
我也是报这个错误，不知你解决了吗？

> 谢谢作者的代码分享，我按照你给的步骤做，运行train_ner.py时，在以下行报错：
> `model = load_model('../data/model/ner_model.h5', custom_objects=get_custom_objects())`
> 错误信息为：
> `OSError: SavedModel file does not exist at: ../data/model/ner_model.h5/{saved_model.pbtxt|saved_model.pb}`
> 请问这个文件第一次运行时怎么生成呢？

**Comment by pen-ho** [comment]
我是直接注释了那一行

**Comment by HankTown** [comment]
> 我是直接注释了那一行

是的，我也是注释掉那一行就可以了
