### ISSUE TITLE
neo4j查询慢的问题

### ISSUE THREAD

**Issue by haojiepan1** [duterscmy/ccks2019-ckbqa-4th-codes#52]
您好，最近在研究知识图谱，调用过程中看看您的开源项目，但是在复现的时候GetRelationPaths每一次查询neo4j要花费36s，这个耗时是否正常？您那边一次查询耗时多久？

**Comment by haojiepan1** [comment]
您好，最近在研究知识图谱，调用过程中看看您的开源项目，但是在复现的时候GetRelationPaths每一次查询neo4j要花费36s，这个耗时是否正常？您那边一次查询耗时多久？

**Comment by dschain** [comment]
同样慢

**Comment by duterscmy** [comment]
src/kb.py里有一句注释的#session.run('CREATE INDEX ON:Entity(name)')是建索引
第一次导入完知识库需要运行一下，之后会快很多
还慢的话可能就是你分配给neo4j内存的问题了

**Comment by duterscmy** [comment]
[https://github.com/duterscmy/ccks2019-ckbqa-4th-codes/issues/29](url) 这个回答解释的比较清楚
