### ISSUE TITLE
tuple_filter.py文件SaveFilterCandiT函数运行error

### ISSUE THREAD

**Issue by dschain** [duterscmy/ccks2019-ckbqa-4th-codes#54]
> def SaveFilterCandiT(corpus,predict_tuples):
    for i in range(len(corpus)):
        candidate_tuple_filter = {}
        for t in predict_tuples[i]:
            features = corpus[i]['candidate_tuples'][t]
            new_features = features[0:2]+[features[9][0][1]]
            candidate_tuple_filter[t] = new_features
        corpus[i]['candidate_tuple_filter'] = candidate_tuple_filter
        #temp =corpus[i].pop('candidate_tuples')
    return corpus

Traceback (most recent call last):
  File "tuple_filter.py", line 205, in <module>
    SaveFilterCandiT(valid_corpus,predict_tuples_valid)
  File "tuple_filter.py", line 165, in SaveFilterCandiT
    new_features = features[0:2]+[features[9][0][1]]
TypeError: 'int' object is not subscriptable

您好，这个没明白，我的features是list，[features[9][0][1]]用法不对吧，应该怎么改？
调了1个多星期了，调到了这里。

**Comment by duterscmy** [comment]
[features[9][0][1]]，这个地方，和features的结构不一致，这块我尽快改下；
你可以自己看下features的结构，把[features[9][0][1]]最后一个换成最后一个特征就好了

**Comment by dschain** [comment]
目前用的 features[0:2]+[features[9]]+[features[0]]+[features[1]]，目前做到每个环节跑通，整个代码意思还不太理解，在理解中
