### ISSUE TITLE
mention_extractor.py结果

### ISSUE THREAD

**Issue by zhengxiaoxuer** [duterscmy/ccks2019-ckbqa-4th-codes#6]
执行mention_extractor.py得到的mention如下，应该得到的是实体，但我得到的结果和分词结果一样。是我的segment.txt的原因吗？结果如下：

维力医疗有哪些高管硕士学历?
{'维力医疗': '维力医疗', '有': '有', '硕士': '硕士', '学历': '学历', '?': '?'}
维力医疗有哪些高管本科学历?
{'维力医疗': '维力医疗', '有': '有', '?': '?'}
维力医疗有哪些高管大专学历?
{'维力医疗': '维力医疗', '有': '有', '大专学历': '大专学历', '?': '?'}
维力医疗的董事长?
{'维力医疗': '维力医疗', '的': '的', '董事长': '董事长', '?': '?'}
维力医疗的第一任董事长?
{'维力医疗': '维力医疗', '的': '的', '董事长': '董事长', '?': '?'}

**Comment by duterscmy** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        这个分词后好像就是这样的。因为在pukubase里面，像“的”“有”这样的mention也可以链接到知识库上。我简单的在实体链接那个文件里写了条词性判断的规则来过滤，你也可以试试找些别的规则处理下。
        
    
        
            
        
    
    
        
        

        
    

    在2019年11月5日 11:15，zhengxiaoxuer<notifications@github.com> 写道： 


执行mention_extractor.py得到的mention如下，应该得到的是实体，但我得到的结果和分词结果一样。是我的segment.txt的原因吗？结果如下：
维力医疗有哪些高管硕士学历?
{'维力医疗': '维力医疗', '有': '有', '硕士': '硕士', '学历': '学历', '?': '?'}
维力医疗有哪些高管本科学历?
{'维力医疗': '维力医疗', '有': '有', '?': '?'}
维力医疗有哪些高管大专学历?
{'维力医疗': '维力医疗', '有': '有', '大专学历': '大专学历', '?': '?'}
维力医疗的董事长?
{'维力医疗': '维力医疗', '的': '的', '董事长': '董事长', '?': '?'}
维力医疗的第一任董事长?
{'维力医疗': '维力医疗', '的': '的', '董事长': '董事长', '?': '?'}

**Comment by zhengxiaoxuer** [comment]
好的，那我继续执行后面程序看一下
